// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btsmnrcaipaqlfbvsnyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0c21ucmNhaXBhcWxmYnZzbnl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2OTE2MzUsImV4cCI6MjA1NTI2NzYzNX0.4s-z5sT5IdNMRgzLt0R885hZAhxx2WDO-v_-ySOb7Fk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);